import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  scrollView: {
    flex: 1,
  },
  scrollContainer: {
    paddingBottom: 80, // Reduced space for fixed button
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#64748B',
    fontWeight: '500',
  },
  headerContainer: {
    paddingTop: 30,
    paddingBottom: 16,
    paddingHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
    marginTop: -25,
  },
  backButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#64748B',
  },
  progressContainer: {
    flex: 1,
    marginLeft: 15,
    alignItems: 'center',
  },
  progressBar: {
    width: '100%',
    height: 8,
    backgroundColor: '#E2E8F0',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4F46E5',
    borderRadius: 4,
  },
  progressText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  contentCard: {
    margin: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 4,
  },
  question: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 16,
    color: '#1E293B',
    lineHeight: 24,
  },
  questionImageContainer: {
    alignItems: 'center',
    marginBottom: 25,
  },
  questionImage: {
    width: 130,
    height: 130,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    resizeMode: 'contain',
  },
  optionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 24,
    gap: 16,
  },
  imageOptionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  textOptionsContainer: {
    flexDirection: 'column',
    marginBottom: 16,
    gap: 14,
  },
  option: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
  },
  textOption: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: '#E0E7FF',
    overflow: 'hidden',
    width: '100%',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 5,
  },
  imageOption: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#E0E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    overflow: 'hidden',
    width: '46%',
    aspectRatio: 1,
  },
  textOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
  },
  imageOptionContent: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    flex: 1,
  },
  imageOptionLetter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#4F46E5',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  imageOptionLetterText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 12,
  },
  imageOptionImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 80,
    height: 80,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    overflow: 'hidden',
    flexShrink: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  optionNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  optionNumberText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 13,
  },
  optionText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
  },
  optionImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
    resizeMode: 'contain',
    backgroundColor: 'transparent',
  },
  imageNotFoundContainer: {
    width: 80,
    height: 80,
    borderRadius: 10,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
  },
  imageNotFoundText: {
    fontSize: 12,
    color: '#9CA3AF',
    textAlign: 'center',
    fontWeight: '500',
  },
  correctOption: {
    backgroundColor: '#DCFCE7',
    borderColor: '#10B981',
    borderWidth: 4,
  },
  incorrectOption: {
    backgroundColor: '#FEE2E2',
    borderColor: '#EF4444',
    borderWidth: 4,
  },
  feedbackContainer: {
    alignItems: 'center',
    marginVertical: 12,
    paddingHorizontal: 16,
    minHeight: 40,
    justifyContent: 'center',
  },
  feedback: {
    fontSize: 16,
    fontWeight: '700',
    color: '#10B981',
    textAlign: 'center',
    lineHeight: 20,
  },
  hintContainer: {
    backgroundColor: '#FEF3C7',
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#F59E0B',
  },
  hintLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#92400E',
    marginBottom: 3,
  },
  hintText: {
    fontSize: 13,
    color: '#92400E',
    lineHeight: 18,
  },
  answerContainer: {
    backgroundColor: '#DCFCE7',
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#059669',
  },
  answerLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#059669',
    marginBottom: 3,
  },
  answerText: {
    fontSize: 14,
    color: '#059669',
    fontWeight: '500',
    marginTop: 3,
    textAlign: 'center',
  },
  fixedBottomContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    alignItems: 'center',
    zIndex: 20,
  },
  nextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4F46E5',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
  nextButtonIcon: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  moodContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  moodCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  moodTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 8,
    textAlign: 'center',
  },
  moodSubtitle: {
    fontSize: 15,
    color: '#64748B',
    marginBottom: 18,
    textAlign: 'center',
  },
  moodGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 12,
  },
  emojiButton: {
    margin: 8,
    padding: 8,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
  },
  emoji: {
    fontSize: 32,
  },
  audioPlayerContainer: {
    marginTop: 5,
    marginBottom: 20,
    alignItems: 'center',
  },
  audioButton: {
    backgroundColor: '#E0E7FF',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  audioButtonText: {
    color: '#3730A3',
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 0.2,
  },
  // Multi-image container styles for Visual Activity Quiz
  multiImageContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 12,
    gap: 12,
    // flexWrap: 'wrap',
    alignSelf: 'center', // This centers the entire container within its parent
  },
  multiImageWrapper: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    // padding: 12,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    minWidth: 100,
  },
  multiImage: {
    // width: 90,
    width: 70,
    // height: 90,
    height: 70,
    borderRadius: 10,
    resizeMode: 'contain',
  },
  multiImageConnector: {
    // fontSize: 24,
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    // marginHorizontal: 6,
    marginHorizontal: 4,
    backgroundColor: '#4F46E5',
    // borderRadius: 20,
    borderRadius: 15,
    // width: 40,
    width: 30,
    // height: 40,
    height: 30,
    textAlign: 'center',
    // lineHeight: 40,
    lineHeight: 30,
    overflow: 'hidden',
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
});

export default styles;
